# Redundant keys are not allowed!
address: 0.0.0.0
port: 25565
bungeecord: false
optfine: true
chunkViewDistance: 16
entityViewDistance: 16
brandName: "ExampleBrandName"
# {cmd} with be replaced with the raw command.
unknownCommandMessage: "未知命令: {cmd}"